In [2]:
import numpy as np

# Parameters
## beta
beta as k x |V| matrix that represents probability that word belongs to topic. initialize to 1/k for each word.

## alpha
probability of topic in the whole corpus represented as |k| size matrix

## term doc matrix
count of words in vocabulary for each document

## pi
word topic distribution for each document (what probability does word belong to topic)

## gamma
topic distribution for each document


In [18]:
# set parameters
k = 2 # number of topics
v = 5 # number of words in vocabulary
d = 3 # number of documents in corpus
e_num_iter = 2 # number of iterations for e-step

In [23]:
alpha = np.array([1/k for i in range(k)])

In [24]:
alpha

array([0.5, 0.5])

In [19]:
beta = np.full((k, v), 1/k)

In [20]:
beta

array([[0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5]])

In [21]:
term_doc_matrix = np.random.randint(10, size=(d, v))

In [22]:
term_doc_matrix

array([[6, 0, 8, 1, 9],
       [8, 7, 2, 4, 6],
       [9, 6, 2, 6, 3]])

In [39]:
gamma = np.full((d, k), alpha)
for i in range(d):
    gamma[i] = gamma[i] + term_doc_matrix[i].sum()/k

In [40]:
gamma

array([[12.5, 12.5],
       [14. , 14. ],
       [13.5, 13.5]])

In [41]:
# check with sum of words in each doc
term_doc_matrix.sum(axis=1)

array([24, 27, 26])

In [ ]:

for i in range(e_num_iter):
    p = []
    for j in range(d):
        p.append(beta * term_doc_matrix